# Generated by Django 5.2.4 on 2025-07-16 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customuser_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "permissions": [
                    ("can_list_users", "Can list users"),
                    ("can_activate_user", "Can activate user"),
                    ("can_deactivate_user", "Can deactivate user"),
                ],
                "verbose_name": "пользователь",
                "verbose_name_plural": "пользователи",
            },
        ),
    ]
