# Generated by Django 5.2.4 on 2025-07-16 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("client_connect", "0002_mailing_owner_message_owner_recipient_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "ordering": ["status"],
                "permissions": [("can_list_mailings", "Can list mailings")],
                "verbose_name": "рассылка",
                "verbose_name_plural": "рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ["subject"],
                "permissions": [("can_list_messages", "Can list messages")],
                "verbose_name": "сообщение",
                "verbose_name_plural": "сообщения",
            },
        ),
        migrations.AlterModelOptions(
            name="recipient",
            options={
                "ordering": ["email"],
                "permissions": [("can_list_recipients", "Can list recipients")],
                "verbose_name": "получатель",
                "verbose_name_plural": "получатели",
            },
        ),
    ]
