# Generated by Django 5.2.4 on 2025-07-16 22:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_connect", "0003_alter_mailing_options_alter_message_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mailing",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="mailing",
            name="update_at",
        ),
        migrations.AddField(
            model_name="mailing",
            name="end_time",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Дата окончания отправки"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mailing",
            name="start_time",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Дата первой отправки"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="sendingattempt",
            name="status",
            field=models.CharField(
                choices=[("success", "Успешно"), ("fail", "Не успешно")], max_length=10, verbose_name="Статус"
            ),
        ),
    ]
