# Generated by Django 5.2.4 on 2025-07-16 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_connect", "0004_remove_mailing_created_at_remove_mailing_update_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Дата окончания отправки"),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="start_time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Дата первой отправки"),
        ),
    ]
