# Generated by Django 5.2.4 on 2025-07-17 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("client_connect", "0005_alter_mailing_end_time_alter_mailing_start_time"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sendingattempt",
            options={
                "ordering": ["status"],
                "permissions": [("can_list_sending_attempts", "Can_list_sending_attempts")],
                "verbose_name": "попытка рассылки",
                "verbose_name_plural": "попытки рассылки",
            },
        ),
    ]
