# Generated by Django 5.2.4 on 2025-07-20 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("client_connect", "0006_alter_sendingattempt_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "ordering": ["status"],
                "permissions": [("can_list_mailings", "Can list mailings"), ("can_disable_send", "Can disable send")],
                "verbose_name": "рассылка",
                "verbose_name_plural": "рассылки",
            },
        ),
    ]
