# Generated by Django 5.2.4 on 2025-07-20 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_connect", "0007_alter_mailing_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[
                    ("done", "Завершена"),
                    ("created", "Создана"),
                    ("launched", "Запущена"),
                    ("disable", "Отключена"),
                ],
                default="created",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
    ]
